name: number_selection
description: Cool number picker concept
version: 1.0.0
author: Ali Rajab nezhad <alirn76@yahoo.com>
homepage: https://github.com/AliRn76/number_selection

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter: